<#import "blocks/template.ftlh" as t>
<@t.template user>

    <head>
        <meta charset="UTF-8">
        <title>Successful Registration</title>
    </head>
    <body>
    <h1>Регистрация прошла успешно!</h1>
    <p>Спасибо за регистрацию. На электронную почту было отправлено письмо для подтверждения вашей учетной записи.</p>
    <!-- Дополнительный контент, если необходимо -->
    </body>
</@t.template>